version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CoinDirectory"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j8iwxotpyec9"
s3_prefix = "CoinDirectory"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
